### ISSUE TITLE
@import seemingly not setup properly

### ISSUE THREAD

**Issue by rvcas** [tbash/elm-starter#3]
While doing some stuff with the starter I noticed that the `@import` in `src/css/index.css` isn't pulling up the styles.

Will a post-css plugin fix it?

or would you just like to do something like this in `src/js/index.js`:

```js
import Elm from '../elm/Main';

import '../css/minireset.css';
import '../css/index.css';

Elm.Main.fullscreen();
```

The second thing is what I am doing for now.

**Comment by tbash** [comment]
fixed in https://github.com/tbash/elm-starter/pull/4
